/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) libExample_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[4] = {3, 1, 0, 0};
static const casadi_int casadi_s4[4] = {4, 1, 0, 0};
static const casadi_int casadi_s5[4] = {1, 1, 0, 0};

/* f:(i0[4],i1)->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1;
  a0=arg[0] ? arg[0][0] : 0;
  a1=arg[1] ? arg[1][0] : 0;
  a0=(a0*a1);
  a0=sin(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][1] : 0;
  a1=sqrt(a1);
  a0=(a0*a1);
  a1=arg[0] ? arg[0][2] : 0;
  a0=(a0-a1);
  a0=cos(a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* fwd1_f:(i0[4],i1,out_o0[3x1,0nz],fwd_i0[4],fwd_i1)->(fwd_o0[3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0] ? arg[0][0] : 0;
  a1=arg[1] ? arg[1][0] : 0;
  a2=(a0*a1);
  a2=cos(a2);
  a3=arg[3] ? arg[3][0] : 0;
  a3=(a1*a3);
  a4=arg[4] ? arg[4][0] : 0;
  a0=(a0*a4);
  a3=(a3+a0);
  a2=(a2*a3);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0] ? arg[0][1] : 0;
  a1=sqrt(a1);
  a3=(a2*a1);
  a0=arg[0] ? arg[0][2] : 0;
  a3=(a3-a0);
  a3=sin(a3);
  a0=arg[3] ? arg[3][1] : 0;
  a0=(a1*a0);
  a1=(a1+a1);
  a4=(a4/a1);
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3] ? arg[3][2] : 0;
  a0=(a0-a2);
  a3=(a3*a0);
  a3=(-a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[3] ? arg[3][3] : 0;
  if (res[0]!=0) res[0][2]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int fwd1_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void fwd1_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void fwd1_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fwd1_f_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int fwd1_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* fwd1_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "out_o0";
    case 3: return "fwd_i0";
    case 4: return "fwd_i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fwd1_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "fwd_o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fwd1_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fwd1_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fwd1_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj1_f:(i0[4],i1,out_o0[3x1,0nz],adj_o0[3])->(adj_i0[4],adj_i1) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[1] ? arg[1][0] : 0;
  a1=arg[0] ? arg[0][0] : 0;
  a2=(a1*a0);
  a2=cos(a2);
  a3=arg[3] ? arg[3][0] : 0;
  a2=(a2*a3);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a0=sqrt(a0);
  a3=arg[0] ? arg[0][1] : 0;
  a4=(a3*a0);
  a5=arg[0] ? arg[0][2] : 0;
  a4=(a4-a5);
  a4=sin(a4);
  a5=arg[3] ? arg[3][1] : 0;
  a4=(a4*a5);
  a5=(a0*a4);
  a5=(-a5);
  if (res[0]!=0) res[0][1]=a5;
  if (res[0]!=0) res[0][2]=a4;
  a5=arg[3] ? arg[3][2] : 0;
  if (res[0]!=0) res[0][3]=a5;
  a1=(a1*a2);
  a3=(a3*a4);
  a0=(a0+a0);
  a3=(a3/a0);
  a1=(a1-a3);
  if (res[1]!=0) res[1][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj1_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj1_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj1_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adj1_f_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int adj1_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adj1_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "out_o0";
    case 3: return "adj_o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj1_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "adj_i0";
    case 1: return "adj_i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj1_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj1_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj1_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* fwd1_adj1_f:(i0[4],i1,out_o0[3x1,0nz],adj_o0[3],out_adj_i0[4x1,0nz],out_adj_i1[1x1,0nz],fwd_i0[4],fwd_i1,fwd_out_o0[3x1,0nz],fwd_adj_o0[3])->(fwd_adj_i0[4],fwd_adj_i1) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][0] : 0;
  a1=arg[1] ? arg[1][0] : 0;
  a2=(a0*a1);
  a3=cos(a2);
  a4=arg[3] ? arg[3][0] : 0;
  a5=(a3*a4);
  a6=arg[7] ? arg[7][0] : 0;
  a7=(a5*a6);
  a8=arg[9] ? arg[9][0] : 0;
  a3=(a3*a8);
  a2=sin(a2);
  a8=arg[6] ? arg[6][0] : 0;
  a9=(a1*a8);
  a10=(a0*a6);
  a9=(a9+a10);
  a2=(a2*a9);
  a4=(a4*a2);
  a3=(a3-a4);
  a4=(a1*a3);
  a7=(a7+a4);
  if (res[0]!=0) res[0][0]=a7;
  a7=arg[0] ? arg[0][1] : 0;
  a1=sqrt(a1);
  a4=(a7*a1);
  a2=arg[0] ? arg[0][2] : 0;
  a4=(a4-a2);
  a2=sin(a4);
  a9=arg[3] ? arg[3][1] : 0;
  a10=(a2*a9);
  a11=(a1+a1);
  a6=(a6/a11);
  a11=(a10*a6);
  a4=cos(a4);
  a12=arg[6] ? arg[6][1] : 0;
  a13=(a1*a12);
  a14=(a7*a6);
  a13=(a13+a14);
  a14=arg[6] ? arg[6][2] : 0;
  a13=(a13-a14);
  a4=(a4*a13);
  a9=(a9*a4);
  a4=arg[9] ? arg[9][1] : 0;
  a2=(a2*a4);
  a9=(a9+a2);
  a2=(a1*a9);
  a11=(a11+a2);
  a11=(-a11);
  if (res[0]!=0) res[0][1]=a11;
  if (res[0]!=0) res[0][2]=a9;
  a11=arg[9] ? arg[9][2] : 0;
  if (res[0]!=0) res[0][3]=a11;
  a5=(a5*a8);
  a0=(a0*a3);
  a5=(a5+a0);
  a12=(a10*a12);
  a9=(a7*a9);
  a12=(a12+a9);
  a1=(a1+a1);
  a12=(a12/a1);
  a7=(a7*a10);
  a7=(a7/a1);
  a7=(a7/a1);
  a6=(a6+a6);
  a7=(a7*a6);
  a12=(a12-a7);
  a5=(a5-a12);
  if (res[1]!=0) res[1][0]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int fwd1_adj1_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void fwd1_adj1_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void fwd1_adj1_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fwd1_adj1_f_n_in(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_int fwd1_adj1_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* fwd1_adj1_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "out_o0";
    case 3: return "adj_o0";
    case 4: return "out_adj_i0";
    case 5: return "out_adj_i1";
    case 6: return "fwd_i0";
    case 7: return "fwd_i1";
    case 8: return "fwd_out_o0";
    case 9: return "fwd_adj_o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fwd1_adj1_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "fwd_adj_i0";
    case 1: return "fwd_adj_i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fwd1_adj1_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    case 6: return casadi_s0;
    case 7: return casadi_s1;
    case 8: return casadi_s3;
    case 9: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fwd1_adj1_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fwd1_adj1_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
