/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) libSolver_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {2, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s3[7] = {1, 2, 0, 1, 2, 0, 0};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* nlp:(x[2],p)->(f,g) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0] ? arg[0][0] : 0;
  a1=casadi_sq(a0);
  a2=arg[0] ? arg[0][1] : 0;
  a3=casadi_sq(a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][0]=a1;
  a0=(a0+a2);
  a2=arg[1] ? arg[1][0] : 0;
  a0=(a0-a2);
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_f:(x[2],p)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1;
  a0=arg[0] ? arg[0][0] : 0;
  a0=casadi_sq(a0);
  a1=arg[0] ? arg[0][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_g:(x[2],p)->(g) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1;
  a0=arg[0] ? arg[0][0] : 0;
  a1=arg[0] ? arg[0][1] : 0;
  a0=(a0+a1);
  a1=arg[1] ? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad:(x[2],p,lam_f,lam_g)->(f,g,grad_gamma_x[2],grad_gamma_p) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0] ? arg[0][0] : 0;
  a1=casadi_sq(a0);
  a2=arg[0] ? arg[0][1] : 0;
  a3=casadi_sq(a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][0]=a1;
  a1=(a0+a2);
  a3=arg[1] ? arg[1][0] : 0;
  a1=(a1-a3);
  if (res[1]!=0) res[1][0]=a1;
  a1=arg[3] ? arg[3][0] : 0;
  a0=(a0+a0);
  a3=arg[2] ? arg[2][0] : 0;
  a0=(a0*a3);
  a0=(a1+a0);
  if (res[2]!=0) res[2][0]=a0;
  a2=(a2+a2);
  a2=(a2*a3);
  a2=(a1+a2);
  if (res[2]!=0) res[2][1]=a2;
  a1=(-a1);
  if (res[3]!=0) res[3][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    case 2: return "grad_gamma_x";
    case 3: return "grad_gamma_p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad_f:(x[2],p)->(f,grad_f_x[2]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0] ? arg[0][0] : 0;
  a1=casadi_sq(a0);
  a2=arg[0] ? arg[0][1] : 0;
  a3=casadi_sq(a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][0]=a1;
  a0=(a0+a0);
  if (res[1]!=0) res[1][0]=a0;
  a2=(a2+a2);
  if (res[1]!=0) res[1][1]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "grad_f_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_hess_l:(x[2],p,lam_f,lam_g)->(hess_gamma_x_x[2x2,2nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2;
  a0=2.;
  a1=arg[2] ? arg[2][0] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i){
  switch (i) {
    case 0: return "hess_gamma_x_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_jac_g:(x[2],p)->(g,jac_g_x[1x2]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1;
  a0=arg[0] ? arg[0][0] : 0;
  a1=arg[0] ? arg[0][1] : 0;
  a0=(a0+a1);
  a1=arg[1] ? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    case 1: return "jac_g_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
